POST http://localhost:63040/test/r/r1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsid21zIl0sInVzZXJfbmFtZSI6InpoYW5nc2FuIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4MTQ1OTk0MywiYXV0aG9yaXRpZXMiOlsicDEiXSwianRpIjoiZmM3NjYwZjAtYjE0NS00NzlkLThjNTItZjU2NDFhMzM4ZDQ3IiwiY2xpZW50X2lkIjoid21zQXBwIn0.ceuojhMmzHa38QF9DLGERQfS8uG_dY2VU_rhgvqVAQY

#POST http://localhost:63050/auth/oauth/token
#Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsid21zIl0sInVzZXJfbmFtZSI6InpoYW5nc2FuIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4MTQ1MDc5NCwiYXV0aG9yaXRpZXMiOlsicDEiXSwianRpIjoiNzk3ODc1ZmYtNzZiYy00YzE0LWIyNzMtMjZhZjIwYTMwZDQxIiwiY2xpZW50X2lkIjoid21zQXBwIn0.VtWucv95z5hjiHV3AYGcsi8FkmB3wIHx2Fcyx1Ge9_Q
#Content-Type: application/json
#
#{
#"refresh_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsid21zIl0sInVzZXJfbmFtZSI6InpoYW5nc2FuIiwic2NvcGUiOlsiYWxsIl0sImF0aSI6Ijc5Nzg3NWZmLTc2YmMtNGMxNC1iMjczLTI2YWYyMGEzMGQ0MSIsImV4cCI6MTY4MTcwMjc5NCwiYXV0aG9yaXRpZXMiOlsicDEiXSwianRpIjoiNWVlYzc3MzMtN2E0Zi00N2IwLWExYWUtMzk5ODZhNjM4NDkwIiwiY2xpZW50X2lkIjoid21zQXBwIn0.5eZjkwwU-KYg0edXAliCEvTLUqkVceqmDeejUpzQNFo",
#"grant_type" : "refresh_token"
#}




